// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

package org.gof.worldsrv;

import org.gof.behaviac.*;
import org.gof.behaviac.members.*;
import java.util.List;
import java.util.ArrayList;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

public class MyAgent extends org.gof.behaviac.Agent
///<<< BEGIN WRITING YOUR CODE MyAgent
///<<< END WRITING YOUR CODE
{
	public static short s1 = 0;
	public static IProperty CreateStaticProperty_S1() {
		CStaticMemberProperty.Getter getter = ()-> { return org.gof.worldsrv.MyAgent.s1; };
		CStaticMemberProperty.Setter setter = (_obj)-> { org.gof.worldsrv.MyAgent.s1 = (Short)_obj; };
		CStaticMemberProperty prop = new CStaticMemberProperty("s1", new ClassInfo(Short.class), getter, setter);
		return prop;
	}

	private static long s2 = 0;
	public static void _set_s2(long value)
	{
		s2 = value;
	}
	public static long _get_s2()
	{
		return s2;
	}
	public static IProperty CreateStaticProperty_S2() {
		CStaticMemberProperty.Getter getter = ()-> { return org.gof.worldsrv.MyAgent.s2; };
		CStaticMemberProperty.Setter setter = (_obj)-> { org.gof.worldsrv.MyAgent.s2 = (Long)_obj; };
		CStaticMemberProperty prop = new CStaticMemberProperty("s2", new ClassInfo(Long.class), getter, setter);
		return prop;
	}

	private org.gof.behaviac.EBTStatus v1 = org.gof.behaviac.EBTStatus.BT_INVALID;
	public void _set_v1(org.gof.behaviac.EBTStatus value)
	{
		v1 = value;
	}
	public org.gof.behaviac.EBTStatus _get_v1()
	{
		return v1;
	}
	public static IProperty CreateMemberProperty_V1() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v1; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v1 = (org.gof.behaviac.EBTStatus)_obj; };
		CMemberProperty prop = new CMemberProperty("v1", new ClassInfo(org.gof.behaviac.EBTStatus.class), getter, setter);
		return prop;
	}

	private ArrayList<org.gof.behaviac.EBTStatus> v11 = new ArrayList<org.gof.behaviac.EBTStatus>();
	public void _set_v11(ArrayList<org.gof.behaviac.EBTStatus> value)
	{
		v11 = value;
	}
	public ArrayList<org.gof.behaviac.EBTStatus> _get_v11()
	{
		return v11;
	}
	public static IProperty CreateMemberProperty_V11() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v11; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v11 = (ArrayList<org.gof.behaviac.EBTStatus>)_obj; };
		CMemberProperty prop = new CMemberProperty("v11", new ClassInfo(true,org.gof.behaviac.EBTStatus.class), getter, setter);
		return prop;
	}

	public static IProperty CreateMemberArrayProperty_V11() {
		CMemberArrayItemProperty.Getter getter = (_agent, _index)-> { return ((org.gof.worldsrv.MyAgent)_agent).v11.get(_index); };
		CMemberArrayItemProperty.Setter setter = (_agent,_obj, _index)-> { ((org.gof.worldsrv.MyAgent)_agent).v11.set(_index, (org.gof.behaviac.EBTStatus)_obj); };
		CMemberArrayItemProperty prop = new CMemberArrayItemProperty("v11[]", new ClassInfo(true,org.gof.behaviac.EBTStatus.class), getter, setter);
		return prop;
	}

	private ArrayList<Boolean> v12 = new ArrayList<Boolean>();
	public void _set_v12(ArrayList<Boolean> value)
	{
		v12 = value;
	}
	public ArrayList<Boolean> _get_v12()
	{
		return v12;
	}
	public static IProperty CreateMemberProperty_V12() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v12; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v12 = (ArrayList<Boolean>)_obj; };
		CMemberProperty prop = new CMemberProperty("v12", new ClassInfo(true,Boolean.class), getter, setter);
		return prop;
	}

	public static IProperty CreateMemberArrayProperty_V12() {
		CMemberArrayItemProperty.Getter getter = (_agent, _index)-> { return ((org.gof.worldsrv.MyAgent)_agent).v12.get(_index); };
		CMemberArrayItemProperty.Setter setter = (_agent,_obj, _index)-> { ((org.gof.worldsrv.MyAgent)_agent).v12.set(_index, (Boolean)_obj); };
		CMemberArrayItemProperty prop = new CMemberArrayItemProperty("v12[]", new ClassInfo(true,Boolean.class), getter, setter);
		return prop;
	}

	private int v13 = 0;
	public void _set_v13(int value)
	{
		v13 = value;
	}
	public int _get_v13()
	{
		return v13;
	}
	public static IProperty CreateMemberProperty_V13() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v13; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v13 = (Integer)_obj; };
		CMemberProperty prop = new CMemberProperty("v13", new ClassInfo(Integer.class), getter, setter);
		return prop;
	}

	private float v14 = 0f;
	public void _set_v14(float value)
	{
		v14 = value;
	}
	public float _get_v14()
	{
		return v14;
	}
	public static IProperty CreateMemberProperty_V14() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v14; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v14 = (Float)_obj; };
		CMemberProperty prop = new CMemberProperty("v14", new ClassInfo(Float.class), getter, setter);
		return prop;
	}

	private double v15 = 0;
	public void _set_v15(double value)
	{
		v15 = value;
	}
	public double _get_v15()
	{
		return v15;
	}
	public static IProperty CreateMemberProperty_V15() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v15; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v15 = (Double)_obj; };
		CMemberProperty prop = new CMemberProperty("v15", new ClassInfo(Double.class), getter, setter);
		return prop;
	}

	private String v16 = "";
	public void _set_v16(String value)
	{
		v16 = value;
	}
	public String _get_v16()
	{
		return v16;
	}
	public static IProperty CreateMemberProperty_V16() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v16; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v16 = (String)_obj; };
		CMemberProperty prop = new CMemberProperty("v16", new ClassInfo(String.class), getter, setter);
		return prop;
	}

	private boolean v2 = false;
	public void _set_v2(boolean value)
	{
		v2 = value;
	}
	public boolean _get_v2()
	{
		return v2;
	}
	public static IProperty CreateMemberProperty_V2() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v2; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v2 = (Boolean)_obj; };
		CMemberProperty prop = new CMemberProperty("v2", new ClassInfo(Boolean.class), getter, setter);
		return prop;
	}

	private int v3 = 0;
	public void _set_v3(int value)
	{
		v3 = value;
	}
	public int _get_v3()
	{
		return v3;
	}
	public static IProperty CreateMemberProperty_V3() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v3; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v3 = (Integer)_obj; };
		CMemberProperty prop = new CMemberProperty("v3", new ClassInfo(Integer.class), getter, setter);
		return prop;
	}

	private int v4 = 0;
	public void _set_v4(int value)
	{
		v4 = value;
	}
	public int _get_v4()
	{
		return v4;
	}
	public static IProperty CreateMemberProperty_V4() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v4; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v4 = (Integer)_obj; };
		CMemberProperty prop = new CMemberProperty("v4", new ClassInfo(Integer.class), getter, setter);
		return prop;
	}

	private float v5 = 0f;
	public void _set_v5(float value)
	{
		v5 = value;
	}
	public float _get_v5()
	{
		return v5;
	}
	public static IProperty CreateMemberProperty_V5() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v5; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v5 = (Float)_obj; };
		CMemberProperty prop = new CMemberProperty("v5", new ClassInfo(Float.class), getter, setter);
		return prop;
	}

	private double v6 = 0;
	public void _set_v6(double value)
	{
		v6 = value;
	}
	public double _get_v6()
	{
		return v6;
	}
	public static IProperty CreateMemberProperty_V6() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v6; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v6 = (Double)_obj; };
		CMemberProperty prop = new CMemberProperty("v6", new ClassInfo(Double.class), getter, setter);
		return prop;
	}

	private String v7 = "";
	public void _set_v7(String value)
	{
		v7 = value;
	}
	public String _get_v7()
	{
		return v7;
	}
	public static IProperty CreateMemberProperty_V7() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.MyAgent)_agent).v7; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.MyAgent)_agent).v7 = (String)_obj; };
		CMemberProperty prop = new CMemberProperty("v7", new ClassInfo(String.class), getter, setter);
		return prop;
	}

	public org.gof.behaviac.EBTStatus m1(Boolean v1, Integer v2, Float v3, String v4, Long v5, ArrayList<Boolean> v11, ArrayList<Integer> v12, Double v13)
	{
///<<< BEGIN WRITING YOUR CODE m1
		return org.gof.behaviac.EBTStatus.BT_INVALID;
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_M1() {
		return new CAgentMethod8<org.gof.behaviac.EBTStatus,Boolean, Integer, Float, String, Long, ArrayList<Boolean>, ArrayList<Integer>, Double>((Agent _agent,Boolean v1, Integer v2, Float v3, String v4, Long v5, ArrayList<Boolean> v11, ArrayList<Integer> v12, Double v13)->{ return ((org.gof.worldsrv.MyAgent)_agent).m1(v1, v2, v3, v4, v5, v11, v12, v13);}, new ClassInfo(org.gof.behaviac.EBTStatus.class), new ClassInfo[]{ new ClassInfo(Boolean.class), new ClassInfo(Integer.class), new ClassInfo(Float.class), new ClassInfo(String.class), new ClassInfo(Long.class), new ClassInfo(true,Boolean.class), new ClassInfo(true,Integer.class), new ClassInfo(Double.class) });
	}
	public static void StaticMethod1(Boolean z1, Double z2)
	{
///<<< BEGIN WRITING YOUR CODE StaticMethod1
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateStaticMethod_STATICMETHOD1() {
		return new CAgentStaticMethodVoid2<Boolean, Double>((Boolean z1, Double z2)->{ org.gof.worldsrv.MyAgent.StaticMethod1(z1, z2);},new ClassInfo[]{ new ClassInfo(Boolean.class), new ClassInfo(Double.class) });
	}
	public void testM2(ArrayList<Float> z1, Integer z2)
	{
///<<< BEGIN WRITING YOUR CODE testM2
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_TESTM2() {
		return new CAgentMethodVoid2<ArrayList<Float>, Integer>((Agent _agent,ArrayList<Float> z1, Integer z2)->{ ((org.gof.worldsrv.MyAgent)_agent).testM2(z1, z2);}, new ClassInfo[]{ new ClassInfo(true,Float.class), new ClassInfo(Integer.class) });
	}
///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

///<<< END WRITING YOUR CODE

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

