// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

package org.gof.worldsrv;


public enum EnumTest
{
	EV1(0),
	EV2(1),
	EV3(2);
	private int val;
	private EnumTest(int val) {} 
	public int intValue() { return this.val; } 
}
