// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

package org.gof.worldsrv;

import org.gof.behaviac.*;
import org.gof.behaviac.members.*;
import java.util.List;
import java.util.ArrayList;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

public class SandEventBeacon extends org.gof.behaviac.Agent
///<<< BEGIN WRITING YOUR CODE SandEventBeacon
///<<< END WRITING YOUR CODE
{
	private ArrayList<Long> group1 = new ArrayList<Long>();
	public void _set_group1(ArrayList<Long> value)
	{
		group1 = value;
	}
	public ArrayList<Long> _get_group1()
	{
		return group1;
	}
	public static IProperty CreateMemberProperty_GROUP1() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.SandEventBeacon)_agent).group1; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.SandEventBeacon)_agent).group1 = (ArrayList<Long>)_obj; };
		CMemberProperty prop = new CMemberProperty("group1", new ClassInfo(true,Long.class), getter, setter);
		return prop;
	}

	public static IProperty CreateMemberArrayProperty_GROUP1() {
		CMemberArrayItemProperty.Getter getter = (_agent, _index)-> { return ((org.gof.worldsrv.SandEventBeacon)_agent).group1.get(_index); };
		CMemberArrayItemProperty.Setter setter = (_agent,_obj, _index)-> { ((org.gof.worldsrv.SandEventBeacon)_agent).group1.set(_index, (Long)_obj); };
		CMemberArrayItemProperty prop = new CMemberArrayItemProperty("group1[]", new ClassInfo(true,Long.class), getter, setter);
		return prop;
	}

	private org.gof.worldsrv.StructTest vars = new org.gof.worldsrv.StructTest();
	public void _set_vars(org.gof.worldsrv.StructTest value)
	{
		vars = value;
	}
	public org.gof.worldsrv.StructTest _get_vars()
	{
		return vars;
	}
	public static IProperty CreateMemberProperty_VARS() {
		CMemberProperty.Getter getter = (_agent)-> { return ((org.gof.worldsrv.SandEventBeacon)_agent).vars; };
		CMemberProperty.Setter setter = (_agent,_obj)-> { ((org.gof.worldsrv.SandEventBeacon)_agent).vars = (org.gof.worldsrv.StructTest)_obj; };
		CMemberProperty prop = new CMemberProperty("vars", new ClassInfo(org.gof.worldsrv.StructTest.class), getter, setter);
		return prop;
	}

	public void createTrigger(Boolean once, ArrayList<Float> pos)
	{
///<<< BEGIN WRITING YOUR CODE createTrigger
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_CREATETRIGGER() {
		return new CAgentMethodVoid2<Boolean, ArrayList<Float>>((Agent _agent,Boolean once, ArrayList<Float> pos)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).createTrigger(once, pos);}, new ClassInfo[]{ new ClassInfo(Boolean.class), new ClassInfo(true,Float.class) });
	}
	public boolean hasHumans()
	{
///<<< BEGIN WRITING YOUR CODE hasHumans
		return false;
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_HASHUMANS() {
		return new CAgentMethod0<Boolean>((Agent _agent)->{ return ((org.gof.worldsrv.SandEventBeacon)_agent).hasHumans();}, new ClassInfo(Boolean.class), new ClassInfo[]{  });
	}
	public void sendAward(Integer item, Integer num)
	{
///<<< BEGIN WRITING YOUR CODE sendAward
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_SENDAWARD() {
		return new CAgentMethodVoid2<Integer, Integer>((Agent _agent,Integer item, Integer num)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).sendAward(item, num);}, new ClassInfo[]{ new ClassInfo(Integer.class), new ClassInfo(Integer.class) });
	}
	public void setHumanTargets(Integer type, String hintText, ArrayList<Float> pos, Integer portalSn, ArrayList<Integer> targetSn, Integer targetNum)
	{
///<<< BEGIN WRITING YOUR CODE setHumanTargets
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_SETHUMANTARGETS() {
		return new CAgentMethodVoid6<Integer, String, ArrayList<Float>, Integer, ArrayList<Integer>, Integer>((Agent _agent,Integer type, String hintText, ArrayList<Float> pos, Integer portalSn, ArrayList<Integer> targetSn, Integer targetNum)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).setHumanTargets(type, hintText, pos, portalSn, targetSn, targetNum);}, new ClassInfo[]{ new ClassInfo(Integer.class), new ClassInfo(String.class), new ClassInfo(true,Float.class), new ClassInfo(Integer.class), new ClassInfo(true,Integer.class), new ClassInfo(Integer.class) });
	}
	public void setVar(String name, ArrayList<Integer> value)
	{
///<<< BEGIN WRITING YOUR CODE setVar
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_SETVAR() {
		return new CAgentMethodVoid2<String, ArrayList<Integer>>((Agent _agent,String name, ArrayList<Integer> value)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).setVar(name, value);}, new ClassInfo[]{ new ClassInfo(String.class), new ClassInfo(true,Integer.class) });
	}
	public void spawnMonster(String name, ArrayList<Integer> sn)
	{
///<<< BEGIN WRITING YOUR CODE spawnMonster
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_SPAWNMONSTER() {
		return new CAgentMethodVoid2<String, ArrayList<Integer>>((Agent _agent,String name, ArrayList<Integer> sn)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).spawnMonster(name, sn);}, new ClassInfo[]{ new ClassInfo(String.class), new ClassInfo(true,Integer.class) });
	}
	public ArrayList<Long> spawnMonster2(ArrayList<Integer> sn, String varname)
	{
///<<< BEGIN WRITING YOUR CODE spawnMonster2
		return null;
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_SPAWNMONSTER2() {
		return new CAgentMethod2<ArrayList<Long>,ArrayList<Integer>, String>((Agent _agent,ArrayList<Integer> sn, String varname)->{ return ((org.gof.worldsrv.SandEventBeacon)_agent).spawnMonster2(sn, varname);}, new ClassInfo(true,Long.class), new ClassInfo[]{ new ClassInfo(true,Integer.class), new ClassInfo(String.class) });
	}
	public org.gof.behaviac.EBTStatus waitMonsterKilled(String name)
	{
///<<< BEGIN WRITING YOUR CODE waitMonsterKilled
		return org.gof.behaviac.EBTStatus.BT_INVALID;
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_WAITMONSTERKILLED() {
		return new CAgentMethod1<org.gof.behaviac.EBTStatus,String>((Agent _agent,String name)->{ return ((org.gof.worldsrv.SandEventBeacon)_agent).waitMonsterKilled(name);}, new ClassInfo(org.gof.behaviac.EBTStatus.class), new ClassInfo[]{ new ClassInfo(String.class) });
	}
	public void waitMonsterKilled2(String name, String signalName)
	{
///<<< BEGIN WRITING YOUR CODE waitMonsterKilled2
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_WAITMONSTERKILLED2() {
		return new CAgentMethodVoid2<String, String>((Agent _agent,String name, String signalName)->{ ((org.gof.worldsrv.SandEventBeacon)_agent).waitMonsterKilled2(name, signalName);}, new ClassInfo[]{ new ClassInfo(String.class), new ClassInfo(String.class) });
	}
	public org.gof.behaviac.EBTStatus waitSignal(String signalName)
	{
///<<< BEGIN WRITING YOUR CODE waitSignal
		return org.gof.behaviac.EBTStatus.BT_INVALID;
///<<< END WRITING YOUR CODE
	}

	public static IMethod CreateMemberMethod_WAITSIGNAL() {
		return new CAgentMethod1<org.gof.behaviac.EBTStatus,String>((Agent _agent,String signalName)->{ return ((org.gof.worldsrv.SandEventBeacon)_agent).waitSignal(signalName);}, new ClassInfo(org.gof.behaviac.EBTStatus.class), new ClassInfo[]{ new ClassInfo(String.class) });
	}
///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

///<<< END WRITING YOUR CODE

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

