// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

package org.gof.worldsrv;

public class StructTest
{
	public int sv1;
	public double sv2;
	public long sv3;
}
