// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

package behaviac;
import java.util.List;

// -------------------
// Customized enums
// -------------------

// -------------------
// Customized structs
// -------------------

namespace testbehaviac
{
	public struct StructTest
	{
		public int sv1;
		public double sv2;
		public long sv3;
	}
}
