// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

namespace org.gof.worldsrv
{
	public enum EnumTest
	{
		EV1,
		EV2,
		EV3,
	}
}

// -------------------
// Customized structs
// -------------------

namespace org.gof.worldsrv
{
	public struct StructTest
	{
		public int sv1;
		public double sv2;
		public bool sv3;
	}
}

namespace org.gof.worldsrv
{
	public struct Haha
	{
		public int sv1;
		public double sv2;
		public long sv3;
	}
}
