// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

package org.gof.worldsrv;

public class Haha
{
	public int sv1;
	public double sv2;
	public double xx3;
}
